[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base = "light"

# frequently across your app's widgets (slider, checkbox, buttons)
primaryColor = "#16C89D"  # oder black? oder des echte AISBACH grün?

# Background color for the main container.
backgroundColor = "#FFFFFF"

# Used as the background for most widgets (sidebar, text input etc.)
secondaryBackgroundColor = "#F7F7F7"

# Font color for the page.
textColor = "#424242"

# Font family for the page. (One of "serif", "sans serif" or "mono")
font = "sans serif"


[client]
# hide the default sidebar menu
# because replaced with st andt menu bar
showSidebarNavigation = false
toolbarMode = "viewer"


[ui]

hideTopBar = true
