app_password = "5500"
API_key_firebase = "AIzaSyCa1-1mknFH4UfzqWoF0D6BBPEPt_w-uNI"
API_key_microsoft_translate = "8d76063985msh92060fbe0da71a5p15bb03jsn98245d6f7558"
API_host_microsoft_translate = "microsoft-translator-text.p.rapidapi.com"
API_key_nlp_translate = "94a49b4899msh9908b0d99defdffp1ef725jsnc3dd0554e2ea"
API_host_nlp_translate = "nlp-translation.p.rapidapi.com"
API_key_deepl = "2c3fc22d-5c1c-490a-e58b-4c9796b6efff"
API_key_openai = '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'
jawg_access_token = 'NGyw4w2jh1hyWaznKFm2jeHBV683qULa1kNHnx862xTBFEXLVkFmU3bs5CX0Nwt2'
mapbox_access_token = 'pk.eyJ1IjoidGVuZGVycG9ydCIsImEiOiJjbGoydzV5cGQxZndrM2VzOWZrOGl2dW55In0.e_ImKcak48etiBb_EXghaw'
tender_db_path = 'data/tenders_db_etimad.yml'
tender_df_path = 'data/tenders_df_etimad.ftr'
tender_df_path_user = 'data/tenders_df_etimad_user.ftr'

[firebase]  # store entire dict with the name firebase
apiKey = "AIzaSyBHMyIntA47BZv7P6PLhwpAT-nyRzzbpWA"
authDomain = "tenderport-auth-f5fa7.firebaseapp.com"
databaseURL = "https://tenderport-auth-f5fa7-default-rtdb.europe-west1.firebasedatabase.app/"
projectId = "tenderport-auth-f5fa7"
storageBucket = "tenderport-auth-f5fa7.appspot.com"
messagingSenderId = "816636915579"
appId = "1:816636915579:web:3c5aaff792ff8dae1a57de"
measurementId = "G-EGHFTR59GX"

[aws_rds]  # store entire dict with the name firebase
ENDPOINT = "tenderport-tenders.ckybqtfom2yc.eu-central-1.rds.amazonaws.com"
PORT = "3306"
USER = "admin"
PASSWORD = "KSA089**"
REGION = "eu-central-1"
DBNAME = "tendersDB"

[pinecone_tenders]
pinecone_env = "us-west4-gcp-free"
pinecone_index = "pinecone-tenders"
pinecone_API_key = "fc17b8c1-4c0b-4f87-a14b-995ea410586d"

[pinecone_subsidies]
pinecone_env = "asia-southeast1-gcp-free"
pinecone_index = "pinecone-subsidies"
pinecone_API_key = "1cb478a7-4f48-4c75-befa-34e8fa507a1b"
